# Site settings
title: Chad Macomber Fitness
email: chad.macomber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The most effective, knowledgeable, and friedliest personal training
  serving the Boston and North Shore area.
baseurl: "" # the subpath of your site, e.g. /blog/
stylizedurl: "chadmacomber.com"
phonenumber: "954-682-5739"
url: "http://chadmacomber.com" # the base hostname & protocol for your site
linkedin: "https://www.linkedin.com/pub/chad-macomber/74/138/567"
rss: "https://fitsquared.wordpress.com/rss"
twitter_username: chadmacomber
github_username:  jekyll

# Build settings
markdown: kramdown
